In [2]:
# numpy : numerical python
import numpy as np
dir (np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [3]:
arr1 = np.array([34,82,65,65,90]) # arrays are iterable objects,multiple values of a same data type
arr1

array([34, 82, 65, 65, 90])

In [3]:
# checks the dimension of the array
arr1.ndim

1

In [4]:
arr1.shape # shape will return the shape of your array

(4,)

In [5]:
arr1.dtype

dtype('int32')

In [6]:
arr2 = np.array([[67,89,78,45],[45,67,78,98],[56,78,78,98]])
arr2

array([[67, 89, 78, 45],
       [45, 67, 78, 98],
       [56, 78, 78, 98]])

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(3, 4)

In [10]:
arr2.dtype

dtype('int32')

In [11]:
np.zeros(16)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones(16)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((7,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [5]:
np.ones((7,7)) * 7

array([[7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.]])

In [18]:
# np.eye: returns a 2-d array with ones on the diagonal and zeros elsewhere
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye (5,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

In [20]:
# to have other numbers on the diagonal
np.eye(8) * 9

array([[9., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 0., 0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0., 0., 0., 0.],
       [0., 0., 0., 9., 0., 0., 0., 0.],
       [0., 0., 0., 0., 9., 0., 0., 0.],
       [0., 0., 0., 0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0., 0., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 9.]])

In [22]:
 # return evenly spaced numbers over a specified interval.returns num evenly spaced samples, calculated over the interval [ start ,stop].
# the endpoint of the interval can optionally be excluded
np.linspace(20,25)

array([20.        , 20.10204082, 20.20408163, 20.30612245, 20.40816327,
       20.51020408, 20.6122449 , 20.71428571, 20.81632653, 20.91836735,
       21.02040816, 21.12244898, 21.2244898 , 21.32653061, 21.42857143,
       21.53061224, 21.63265306, 21.73469388, 21.83673469, 21.93877551,
       22.04081633, 22.14285714, 22.24489796, 22.34693878, 22.44897959,
       22.55102041, 22.65306122, 22.75510204, 22.85714286, 22.95918367,
       23.06122449, 23.16326531, 23.26530612, 23.36734694, 23.46938776,
       23.57142857, 23.67346939, 23.7755102 , 23.87755102, 23.97959184,
       24.08163265, 24.18367347, 24.28571429, 24.3877551 , 24.48979592,
       24.59183673, 24.69387755, 24.79591837, 24.89795918, 25.        ])

In [23]:
np.linspace(12,25,15)

array([12.        , 12.92857143, 13.85714286, 14.78571429, 15.71428571,
       16.64285714, 17.57142857, 18.5       , 19.42857143, 20.35714286,
       21.28571429, 22.21428571, 23.14285714, 24.07142857, 25.        ])

In [6]:
arr3 = np.arange(1,101)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr4 = np.arange(1,101,3)
arr4
#

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [7]:
arr5 = np.random.randint(10,80)
arr5

76

In [14]:
np.random.seed(5)
arr6 = np.random.randint(10,80,100)
arr6

array([71, 26, 18, 72, 37, 40, 17, 25, 63, 37, 54, 75, 57, 40, 28, 19, 51,
       72, 11, 26, 15, 68, 10, 14, 46, 61, 37, 41, 12, 78, 48, 29, 28, 17,
       40, 72, 21, 77, 75, 65, 13, 37, 39, 43, 17, 26, 24, 41, 19, 48, 57,
       26, 15, 44, 55, 69, 34, 23, 41, 42, 54, 15, 24, 57, 10, 17, 26, 74,
       18, 54, 47, 15, 32, 62, 79, 70, 39, 45, 30, 59, 42, 23, 28, 62, 32,
       68, 59, 14, 46, 51, 30, 42, 20, 41, 25, 32, 19, 73, 24, 76])

In [16]:
arr7 = arr6.reshape(10,10)
arr7

array([[71, 26, 18, 72, 37, 40, 17, 25, 63, 37],
       [54, 75, 57, 40, 28, 19, 51, 72, 11, 26],
       [15, 68, 10, 14, 46, 61, 37, 41, 12, 78],
       [48, 29, 28, 17, 40, 72, 21, 77, 75, 65],
       [13, 37, 39, 43, 17, 26, 24, 41, 19, 48],
       [57, 26, 15, 44, 55, 69, 34, 23, 41, 42],
       [54, 15, 24, 57, 10, 17, 26, 74, 18, 54],
       [47, 15, 32, 62, 79, 70, 39, 45, 30, 59],
       [42, 23, 28, 62, 32, 68, 59, 14, 46, 51],
       [30, 42, 20, 41, 25, 32, 19, 73, 24, 76]])

In [19]:
arr7[5,6] # to pick a number on a particuerlar row and column

34

In [35]:
# return it back to one row 
arr7 = arr7.flatten()
arr7

array([71, 26, 18, 72, 37, 40, 17, 25, 63, 37, 54, 75, 57, 40, 28, 19, 51,
       72, 11, 26, 15, 68, 10, 14, 46, 61, 37, 41, 12, 78, 48, 29, 28, 17,
       40, 72, 21, 77, 75, 65, 13, 37, 39, 43, 17, 26, 24, 41, 19, 48, 57,
       26, 15, 44, 55, 69, 34, 23, 41, 42, 54, 15, 24, 57, 10, 17, 26, 74,
       18, 54, 47, 15, 32, 62, 79, 70, 39, 45, 30, 59, 42, 23, 28, 62, 32,
       68, 59, 14, 46, 51, 30, 42, 20, 41, 25, 32, 19, 73, 24, 76])

In [36]:
np.sum(arr7)

4040

In [37]:
np.mean(arr7)

40.4

In [38]:
np.median(arr7)

39.5

In [39]:
np.var(arr7)

401.4200000000001

In [40]:
np.sqrt(arr7)

array([8.42614977, 5.09901951, 4.24264069, 8.48528137, 6.08276253,
       6.32455532, 4.12310563, 5.        , 7.93725393, 6.08276253,
       7.34846923, 8.66025404, 7.54983444, 6.32455532, 5.29150262,
       4.35889894, 7.14142843, 8.48528137, 3.31662479, 5.09901951,
       3.87298335, 8.24621125, 3.16227766, 3.74165739, 6.78232998,
       7.81024968, 6.08276253, 6.40312424, 3.46410162, 8.83176087,
       6.92820323, 5.38516481, 5.29150262, 4.12310563, 6.32455532,
       8.48528137, 4.58257569, 8.77496439, 8.66025404, 8.06225775,
       3.60555128, 6.08276253, 6.244998  , 6.55743852, 4.12310563,
       5.09901951, 4.89897949, 6.40312424, 4.35889894, 6.92820323,
       7.54983444, 5.09901951, 3.87298335, 6.63324958, 7.41619849,
       8.30662386, 5.83095189, 4.79583152, 6.40312424, 6.4807407 ,
       7.34846923, 3.87298335, 4.89897949, 7.54983444, 3.16227766,
       4.12310563, 5.09901951, 8.60232527, 4.24264069, 7.34846923,
       6.8556546 , 3.87298335, 5.65685425, 7.87400787, 8.88819